const STORAGE_PREFIX = 'cargoexpress_payment_return_v1_';

const getStorage = (storage) => storage || globalThis.localStorage;

/**
 * Only navigation paths generated by CargoExpress are accepted here. This is
 * a navigation hint, never a payment-verification input; the return token is
 * still verified by the public Edge Function.
 */
export const sanitizeInternalReturnPath = (value, origin = globalThis.location?.origin) => {
  if (typeof value !== 'string' || !value.trim() || !origin) return null;

  const candidate = value.trim();
  if (!candidate.startsWith('/') || candidate.startsWith('//') || candidate.includes('\\')) return null;

  try {
    const parsed = new URL(candidate, origin);
    if (parsed.origin !== origin || !parsed.pathname.startsWith('/')) return null;
    return `${parsed.pathname}${parsed.search}`;
  } catch {
    return null;
  }
};

const keyFor = (returnToken) => `${STORAGE_PREFIX}${returnToken}`;

/**
 * Saves only a same-browser navigation capability. Device B will not have
 * this record, so even a logged-in unrelated account remains on the public
 * confirmation page.
 */
export const savePaymentReturnContext = ({ returnToken, returnTo, userId, role }, storage) => {
  const safeReturnTo = sanitizeInternalReturnPath(returnTo);
  if (!returnToken || !safeReturnTo || !userId || !['admin', 'customer'].includes(role)) return false;

  try {
    getStorage(storage).setItem(keyFor(returnToken), JSON.stringify({
      version: 1,
      returnToken,
      returnTo: safeReturnTo,
      userId,
      role,
      createdAt: Date.now(),
    }));
    return true;
  } catch {
    return false;
  }
};

export const getPaymentReturnContext = (returnToken, storage) => {
  if (!returnToken) return null;

  try {
    const saved = JSON.parse(getStorage(storage).getItem(keyFor(returnToken)) || 'null');
    const safeReturnTo = sanitizeInternalReturnPath(saved?.returnTo);
    if (
      saved?.version !== 1
      || saved.returnToken !== returnToken
      || !safeReturnTo
      || typeof saved.userId !== 'string'
      || !['admin', 'customer'].includes(saved.role)
    ) return null;
    return { ...saved, returnTo: safeReturnTo };
  } catch {
    return null;
  }
};

export const clearPaymentReturnContext = (returnToken, storage) => {
  if (!returnToken) return;
  try {
    getStorage(storage).removeItem(keyFor(returnToken));
  } catch {
    // Cleanup is best-effort; it never affects the confirmed result.
  }
};
