#!/usr/bin/env python3
"""Build a schema-only replica of the LIVE public/private schemas for PGlite.

READ-ONLY: every statement sent to the linked project is a catalog SELECT.
No application rows are read. Output: live-schema.sql (DDL only).

Usage (from repo root, with the Supabase CLI linked):
    python3 scripts/db-simplification-pgtest/snapshot-live-schema.py
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'live-schema.sql')
SCHEMAS = "('public','private')"

def q(sql):
    r = subprocess.run(['supabase', 'db', 'query', '--linked', sql], capture_output=True, text=True)
    t = r.stdout
    if '{' not in t:
        sys.exit(f'query failed: {r.stderr[:500]}')
    return json.loads(t[t.index('{'):])['rows']

cols = q(f"""
select n.nspname s, c.relname t, a.attnum, a.attname col,
       format_type(a.atttypid, a.atttypmod) typ, a.attnotnull nn,
       pg_get_expr(d.adbin, d.adrelid) def, a.attidentity ident
from pg_attribute a join pg_class c on c.oid=a.attrelid
join pg_namespace n on n.oid=c.relnamespace
left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
where n.nspname in {SCHEMAS} and c.relkind in ('r','p') and a.attnum>0 and not a.attisdropped
""")
cons = q(f"""
select n.nspname s, c.relname t, co.conname, co.contype, pg_get_constraintdef(co.oid) def
from pg_constraint co join pg_class c on c.oid=co.conrelid join pg_namespace n on n.oid=c.relnamespace
where n.nspname in {SCHEMAS}
""")
idx = q(f"""
select i.indexdef def from pg_indexes i
where i.schemaname in {SCHEMAS}
  and not exists (select 1 from pg_constraint co where co.conname=i.indexname and co.connamespace=(select oid from pg_namespace where nspname=i.schemaname))
""")
funcs = q(f"""
select pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid=p.pronamespace
where n.nspname in {SCHEMAS} and p.prokind='f'
  and not exists (select 1 from pg_depend d where d.objid=p.oid and d.deptype='e')
""")
trig = q(f"""
select pg_get_triggerdef(t.oid) def from pg_trigger t join pg_class c on c.oid=t.tgrelid
join pg_namespace n on n.oid=c.relnamespace where n.nspname in {SCHEMAS} and not t.tgisinternal
""")
rls = q(f"""
select n.nspname s, c.relname t, c.relrowsecurity r, c.relforcerowsecurity f from pg_class c
join pg_namespace n on n.oid=c.relnamespace where n.nspname in {SCHEMAS} and c.relkind='r'
""")
pol = q(f"""
select n.nspname s, c.relname t, p.polname, p.polcmd, p.polpermissive perm,
  array(select case when r=0 then 'public' else pg_get_userbyid(r) end from unnest(p.polroles) r) roles,
  pg_get_expr(p.polqual, p.polrelid) qual, pg_get_expr(p.polwithcheck, p.polrelid) chk
from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace
where n.nspname in {SCHEMAS}
""")
grants = q(f"""
select table_schema s, table_name t, grantee, string_agg(privilege_type, ', ') privs
from information_schema.role_table_grants
where table_schema in {SCHEMAS} and grantee in ('anon','authenticated','service_role')
group by 1,2,3
""")

out = []
w = out.append
w('-- GENERATED by snapshot-live-schema.py from the LIVE project catalog (schema only, no rows).')
w('SET check_function_bodies = off;')
w('CREATE SCHEMA IF NOT EXISTS private;')
tables = {}
for c in sorted(cols, key=lambda r: (r['s'], r['t'], r['attnum'])):
    tables.setdefault((c['s'], c['t']), []).append(c)
for (s, t), cs in sorted(tables.items()):
    lines = []
    for c in cs:
        d = f'  "{c["col"]}" {c["typ"]}'
        if c['ident'] == 'a': d += ' GENERATED ALWAYS AS IDENTITY'
        elif c['ident'] == 'd': d += ' GENERATED BY DEFAULT AS IDENTITY'
        elif c['def']: d += f' DEFAULT {c["def"]}'
        if c['nn']: d += ' NOT NULL'
        lines.append(d)
    w(f'CREATE TABLE {s}.{t} (\n' + ',\n'.join(lines) + '\n);')
order = {'p': 0, 'u': 1, 'c': 2, 'x': 3, 'f': 4}
for c in sorted(cons, key=lambda r: order.get(r['contype'], 9)):
    w(f'ALTER TABLE {c["s"]}.{c["t"]} ADD CONSTRAINT "{c["conname"]}" {c["def"]};')
for f in funcs:
    w(f['def'].rstrip() + ';')
for i in idx:
    w(i['def'] + ';')
for t in trig:
    w(t['def'] + ';')
for r in rls:
    if r['r']: w(f'ALTER TABLE {r["s"]}.{r["t"]} ENABLE ROW LEVEL SECURITY;')
    if r['f']: w(f'ALTER TABLE {r["s"]}.{r["t"]} FORCE ROW LEVEL SECURITY;')
cmd = {'r': 'SELECT', 'a': 'INSERT', 'w': 'UPDATE', 'd': 'DELETE', '*': 'ALL'}
for p in pol:
    roles = p['roles'] if isinstance(p['roles'], list) else p['roles'].strip('{}').split(',')
    st = f'CREATE POLICY "{p["polname"]}" ON {p["s"]}.{p["t"]} AS {"PERMISSIVE" if p["perm"] else "RESTRICTIVE"} FOR {cmd[p["polcmd"]]} TO {", ".join(roles)}'
    if p['qual']: st += f' USING ({p["qual"]})'
    if p['chk']: st += f' WITH CHECK ({p["chk"]})'
    w(st + ';')
for g in grants:
    w(f'GRANT {g["privs"]} ON {g["s"]}.{g["t"]} TO {g["grantee"]};')
open(OUT, 'w').write('\n'.join(out) + '\n')
print(f'wrote {OUT}: {len(tables)} tables, {len(cons)} constraints, {len(funcs)} functions, {len(trig)} triggers, {len(pol)} policies')
