// Supabase Edge Function: unsubscribe-announcements
//
// Public, no-auth link target (verify_jwt = false in config.toml) — a
// recipient clicks this straight from an email client, so it cannot send an
// Authorization header. Authorization instead comes from an HMAC token bound
// to the specific email address, generated by broadcast-announcement's
// signUnsubscribeToken(); this endpoint can only unsubscribe the address the
// token was signed for, never an arbitrary one.
//
// Flips wants_announcements to false everywhere that address appears —
// profiles (registered customers) and contact_inquiries (public leads) —
// since a person shouldn't have to know which list they're on to leave it.
//
// Required Supabase secrets:
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
//   UNSUBSCRIBE_SIGNING_SECRET — must match broadcast-announcement's value

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4'

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'content-type',
}

function html(body: string, status = 200) {
  return new Response(
    `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
      <title>Email Preferences</title>
      <style>
        body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;background:#F5F7F4;color:#1B2320;
             display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;padding:24px;}
        .card{background:#fff;border-radius:12px;padding:32px;max-width:420px;text-align:center;
              box-shadow:0 1px 2px rgba(0,0,0,.04),0 6px 20px -8px rgba(0,0,0,.1);}
        h1{font-size:1.25rem;margin:0 0 8px;} p{color:#57635D;line-height:1.5;margin:0;}
      </style></head>
      <body><div class="card">${body}</div></body></html>`,
    { status, headers: { 'Content-Type': 'text/html; charset=utf-8', ...CORS_HEADERS } },
  )
}

const hex = (bytes: ArrayBuffer) =>
  Array.from(new Uint8Array(bytes)).map(b => b.toString(16).padStart(2, '0')).join('')

const timingSafeEqual = (a: string, b: string) => {
  if (a.length !== b.length) return false
  let result = 0
  for (let i = 0; i < a.length; i++) result |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return result === 0
}

async function expectedToken(email: string): Promise<string> {
  const secret = Deno.env.get('UNSUBSCRIBE_SIGNING_SECRET') ?? ''
  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign'],
  )
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(email.toLowerCase().trim()))
  return hex(sig).slice(0, 32)
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS_HEADERS })

  const url = new URL(req.url)
  const email = (url.searchParams.get('email') || '').trim()
  const token = (url.searchParams.get('token') || '').trim()

  if (!email || !token) {
    return html('<h1>Missing link details</h1><p>This unsubscribe link is incomplete. Please use the link from the email exactly as sent.</p>', 400)
  }

  const expected = await expectedToken(email)
  if (!timingSafeEqual(expected, token)) {
    return html('<h1>Link not valid</h1><p>We could not verify this unsubscribe link. If you keep seeing this, contact support instead.</p>', 403)
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
  const supabase = createClient(supabaseUrl, serviceRoleKey)

  const { error: profileError } = await supabase
    .from('profiles')
    .update({ wants_announcements: false })
    .ilike('email', email)
  const { error: inquiryError } = await supabase
    .from('contact_inquiries')
    .update({ wants_announcements: false })
    .ilike('contact_email', email)

  if (profileError || inquiryError) {
    console.error('[unsubscribe-announcements] update failed:', profileError?.message, inquiryError?.message)
    return html('<h1>Something went wrong</h1><p>We could not update your preference just now. Please try again shortly.</p>', 500)
  }

  return html(`<h1>You're unsubscribed</h1><p>${email} will no longer receive CargoExpress PH announcement emails. You can re-enable this anytime from your profile if you have an account.</p>`)
})
